### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by rcemper** [HBTGmbH/xml-to-udl#1]
C:\GitHub\xml-to-udl>**docker build -t xml-to-udl:latest**
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

this doesn't work in Win docker desktop

**Comment by heyding** [comment]
You forgot the "." at the end. The readme says: `docker build -t xml-to-udl:latest .`

**Comment by rcemper** [comment]
Thanks fo the hint:
In README.md  this isolated dos just warpped around to the next line !
