### ISSUE TITLE
run the container fails

### ISSUE THREAD

**Issue by rcemper** [HBTGmbH/xml-to-udl#2]
win docker desktop:

docker run --rm -v "${pwd}/studio-export.xml:/irisrun/export.xml" -v "${pwd}/src:/irisrun/udl-export" xml-to-udl:latest
>>>
docker: Error response from daemon: create ${pwd}/studio-export.xml: "${pwd}/studio-export.xml" 
includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. 
If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by rcemper** [comment]
simple docker build  works    >>>> result :   xml-to-udl-iris

**Comment by rcemper** [comment]
this worked:
docker run --rm -v ./studio-export.xml:/irisrun/export.xml -v ./src:/irisrun/udl-export xml-to-udl-iris

**Comment by heyding** [comment]
Windows users should use the PowerShell for executing the docker commands that are mentioned in the README (e.g. ${pwd} only works in the PowerShell).
