### ISSUE TITLE
docker doesn't stop

### ISSUE THREAD

**Issue by rcemper** [HBTGmbH/xml-to-udl#3]
after completion it ends:

Exporting to XML started on 01/24/2023 22:39:32
Exporting project: SampleProject.prj
Export finished successfully.

Exporting File: Utils.HBTLib.INC
Filename: /irisrun/udl-export/Utils/HBTLib.INC
1

**USER>
<ENDOFFILE>
<ERRTRAP>
Successfully Converted!
01/24/23-22:39:35:185 (630) 0 [Utility.Event] Shutting down InterSystems IRIS**
01/24/23-22:39:35:251 (611) 0 [Utility.Event] [SYSTEM MONITOR] System Monitor stopped in %SYS
01/24/23-22:39:36:252 (630) 0 [Utility.Event] Notifying Clients
01/24/23-22:39:36:252 (630) 0 [Utility.Event] No user shutdown routines to execute
01/24/23-22:39:36:255 (630) 0 [Utility.Event] Stopping User Jobs

iris is shut down. but the container hangs and requires manual stopping.

**Comment by heyding** [comment]
That's an issue that we couldn't resolve so far. I will need to do some more research to fix that.

**Comment by heyding** [comment]
Hi Robert, thanks for your input. The container will now stop automatically after the conversion is done.
